[admin]
see_own_notes   = true
deadmin_on_join = true

[discord]
rich_main_icon_id = "einstein-engines"

[game]
hostname           = "Frostbite Station[LightRP - MediumRP/LowRP+][EN] 18+"
desc               = "18+ furry LowRP+/LightRP - MediumRP SS14 server downstreaming from Einstein Engines code and Dangercode, gameplay a mix between Roleplay and Chaos and some Admemery!"
soft_max_players   = 80
lobbyenabled       = true
lobbyduration      = 240

[hub]
tags = "lang:en-US,region:am_n_e,rp:low"
hub_urls = "https://hub.spacestation14.com/, https://web.networkgamez.com/, https://hub.singularity14.co.uk/"

[ic]
flavor_text = true

[infolinks]
discord    = "https://discord.gg/9pTk8p4rMQ"
github     = "https://github.com/Simple-Station/Einstein-Engines"
website    = "https://simplestation.org/"
bug_report = "https://github.com/Frost-Station/Frostbite-Station/issues"

[net]
max_connections = 1024
tickrate = 30

[netres]
limit = 10.0

[build]
#! PLEASE set this for your fork
fork_id = "EinsteinEngines"

[server]
rules_file   = "DefaultRuleset"

[ooc]
enable_during_round = true

[vote]
restart_required_ratio = 0.7
preset_enabled = true
map_enabled = true

#[worldgen]
#enabled = true
